import { ReactNode } from "react";
import { NextPage } from "next";
import { NextAuthProvider } from "@/providers/nextAuthProvider";
import { Inter } from "next/font/google";
import Header from "@/components/header/header";
import Footer from "@/components/footer/footer";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import "./globals.css";
import CategoryList from "@/components/category-list/category-list";
import Providers from "@/components/Providers";
import { Metadata } from "next";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: ReactNode;
}

const RootLayout: NextPage<RootLayoutProps> = ({ children }) => {
  return (
    <NextAuthProvider>
      <html lang="en">
        <body className={inter.className}>
          <Providers>
            <Header />
            <main>
              <div className="flex container">{children}</div>
            </main>
            <Footer />
            <ToastContainer autoClose={3000} />
          </Providers>
        </body>
      </html>
    </NextAuthProvider>
  );
};

export default RootLayout;
